"""Generate reviewed Keychron presets from pinned sources; no HID access.

Overrides below are physical UAP key identities, not guesses based on captions.
Source: overlay/Soup/soup/AnalogueKeyboard.cpp layout_keychron_{k2,q3,q5}_he.
"""
import argparse
import hashlib
import json
from pathlib import Path
import layout_import as m
import keychron_firmware_keymap as firmware

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT/'docs/research/keychron-catalog-sources'
OUTPUT = ROOT/'docs/exports/keychron-he'
HEADER = ROOT/'src/HallJoyProject/HallJoy/keychron_catalog_layouts.h'
IDENTITIES = ROOT/'src/HallJoyProject/HallJoy/keychron_layout_identities.h'
MODELS = [
    ('k2', 'k2_he/ansi_rgb', 0x0E20, {
        '0,15': ('RGB_MOD', 0x404, 'RGB'), '5,10': ('FN_WIN', 0x409, 'Fn')}),
    ('q3', 'q3_he/ansi_encoder', 0x0B30, {
        '5,5': ('KC_MUTE', None, 'Knob'), '0,14': ('KC_CTANA', 0x403, 'Cortana'),
        '0,15': ('RGB_MOD', 0x404, 'RGB'), '5,11': ('FN_WIN', 0x409, 'Fn')}),
    ('q5', 'q5_he/ansi_encoder', 0x0B50, {
        '0,15': ('_______', 0x403, 'F13'), '0,16': ('_______', 0x404, 'F14'),
        '0,17': ('_______', 0x405, 'F15'), '0,18': ('KC_MUTE', None, 'Knob'),
        '5,10': ('FN_WIN', 0x409, 'Fn')}),
]

# Exact factory sources, including region-specific matrix positions. These are
# physical layer/RGB identities in HallJoy's existing UAP convention. Encoders
# are excluded: a consumer mute action is not a keyboard-page mute usage.
MORE = [
    ('k2_iso','k2_he/iso',0x0E21), ('k2_jis','k2_he/jis',0x0E22),
    ('k4_iso','k4_he/iso',0x0E41), ('k4_jis','k4_he/jis',0x0E42),
    ('k8_ansi','k8_he/ansi',0x0E80), ('k8_iso','k8_he/iso',0x0E81), ('k8_jis','k8_he/jis',0x0E82),
    ('k10_ansi','k10_he/ansi',0x0EA0), ('k10_iso','k10_he/iso',0x0EA1),
    ('q1_iso','q1_he/iso_encoder',0x0B11), ('q1_jis','q1_he/jis_encoder',0x0B12),
    ('q3_iso','q3_he/iso_encoder',0x0B31), ('q3_jis','q3_he/jis_encoder',0x0B32),
    ('q5_iso','q5_he/iso_encoder',0x0B51), ('q5_jis','q5_he/jis_encoder',0x0B52),
    ('q6_ansi','q6_he/ansi_encoder',0x0B60), ('q6_iso','q6_he/iso_encoder',0x0B61), ('q6_jis','q6_he/jis_encoder',0x0B62),
    ('q12_ansi','q12_he/ansi_encoder',0x0BC0), ('q12_iso','q12_he/iso_encoder',0x0BC1),
]


def reviewed_fixes(model, definition, info, code):
    unresolved = m.convert(definition, info, code, 'WIN_BASE')['unresolved']
    fixes = {}
    if model == 'q5_iso':
        # Unlike ANSI/JIS, ISO spells these actions out instead of inheriting
        # them. Their physical UAP identities are still OEM 1/2/3, not F13..15.
        factory = m.factory_map(info,code,'WIN_BASE')
        for col in (15,16,17):
            token = 'KC_F'+str(col-2)
            m.require(factory[0,col] == token, 'Q5 ISO physical key changed')
            fixes[f'0,{col}'] = (token,0x403+col-15,'F'+str(col-2))
    for key in unresolved:
        token = key['token']
        position = ','.join(map(str,key['matrix']))
        if token in ('FN_WIN','MO(WIN_FN)'):
            value = (0x409, 'Fn')
        elif token == 'UG_NEXT':
            value = (0x404, 'RGB')
        elif token == 'KC_CTANA':
            value = (0x403, 'Cortana')
        elif token == 'KC_MUTE' and model.startswith('q'):
            value = (None, 'Knob')
        elif token == '_______' and model == 'q5_jis' and position in ('0,15','0,16','0,17'):
            value = (0x403+key['matrix'][1]-15, 'F'+str(key['matrix'][1]-2))
        else:
            raise m.ImportErrorDetail(f'Unreviewed {model}: {key}')
        fixes[position] = (token,*value)
    return fixes


def products():
    result = {}
    header = ['// Generated by tools/build_keychron_layouts.py; do not hand-edit.', '#pragma once']
    identities = []
    names = []
    for model, path, pid, fixes in MODELS + [(a,b,c,None) for a,b,c in MORE] + [(a,'firmware',b,None) for a,b,_,_ in firmware.TABLES]:
        vpid = 0x34340000 + pid
        inputs = {'launcher': SOURCE/(str(vpid)+'-launcher.json'),
                  'info': SOURCE/('qmk' if fixes is not None else 'qmk-2025q3')/path/('info.json' if fixes is not None else 'keyboard.json'),
                  'keymap': SOURCE/('qmk' if fixes is not None else 'qmk-2025q3')/path/'keymaps/default/keymap.c'}
        offset = None
        if path == 'firmware':
            inputs,definition,info,code,fixes,offset = firmware.prepare(SOURCE,model,pid)
        else:
            definition = m.read_json(inputs['launcher'])[0]
            info = m.read_json(inputs['info'])[0]
            code = m.read_source(inputs['keymap'])[0]
            if fixes is None:
                fixes = reviewed_fixes(model, definition, info, code)
        overrides = {}
        for position, (token, hid, label) in fixes.items():
            value = dict(vendorProductId=vpid, token=token,
                         reason=f'Reviewed UAP {model.upper()} physical matrix identity at {position}')
            if hid is None:
                value.update(exclude=True)
            else:
                value.update(hid=hid, label=label)
            overrides[position] = value
        report = m.convert(definition, info, code, 'WIN_BASE', overrides)
        m.require(report['status'] == 'ready', 'Unreviewed actions remain')
        parts = model.split('_')
        family, variant = parts[0],parts[-1] if len(parts)>1 else 'ansi'
        report['name'] = f'Keychron {family.upper()} HE '+('8K ' if '8k' in parts else '')+variant.upper()
        if offset is not None:
            report['factoryTableOffset'] = offset
        identities.append((pid, definition['matrix']['rows'], definition['matrix']['cols'], report['name']))
        names.append((model,report['name']))
        report['sources'] = {key: dict(path=p.relative_to(ROOT).as_posix(), sha256=hashlib.sha256(p.read_bytes()).hexdigest()) for key,p in inputs.items()}
        result[OUTPUT/(report['name']+'.ini')] = m.ini_text(report).encode('utf-16')
        result[OUTPUT/(model+'-review.json')] = (json.dumps(report, indent=2)+'\n').encode()
        header.append(f'static const KeyDef g_catalog_{model}[] = {{')
        for key in report['keys']:
            label = json.dumps(key['label'], ensure_ascii=True)
            fields = [key['hid'], key['y']//46, key['x'], key['w'], key['h'], key['y']]
            if key.get('notchW'):
                fields += [key['notchW'],key['notchY']]
            header.append('    {L%s, %s},' % (label, ', '.join(map(str,fields))))
        header.append('};')
    result[HEADER] = ('\n'.join(header)+'\n').encode()
    registry = ['// Generated by tools/build_keychron_layouts.py.', '#pragma once', '#define HALLJOY_KEYCHRON_CATALOG_PRESETS \\']
    registry += [f'    {{ L"{name}", g_catalog_{model}, (int)std::size(g_catalog_{model}), L"Keychron" }},' + (' \\' if i+1<len(names) else '') for i,(model,name) in enumerate(names)]
    result[HEADER.with_name('keychron_catalog_presets.h')] = ('\n'.join(registry)+'\n').encode()
    table = ['// Generated exact identities; geometry and matrix verified offline.', '#pragma once',
             'namespace halljoy::layout_selection {',
             'struct Identity { unsigned pid, rows, columns; const wchar_t* name; };',
             'inline constexpr Identity kKeychronLayouts[] = {',
             '    {0x0E40,6,19,L"Keychron K4 HE ANSI - Imported"},',
             '    {0x0B10,6,15,L"Keychron Q1 HE ANSI - Imported"},']
    table += [f'    {{0x{pid:04X},{rows},{cols},L"{name}"}},' for pid,rows,cols,name in identities]
    table += ['};','}']
    result[IDENTITIES] = ('\n'.join(table)+'\n').encode()
    return result


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--update', action='store_true', help='Regenerate reviewed outputs after backing up the source tree')
    args = parser.parse_args()
    outputs = products()
    previous = {path:path.read_bytes() if path.exists() else None for path in outputs}
    for path, data in outputs.items():
        if args.check:
            m.require(path.read_bytes() == data, f'Stale generated file: {path}')
        elif args.update:
            m.require((path.read_bytes() if path.exists() else None) == previous[path], f'Concurrent change: {path}')
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        elif path.exists():
            m.require(path.read_bytes() == data, f'Refusing to overwrite changed generated file: {path}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open('xb') as stream:
                stream.write(data)
    print(f'KEYCHRON_CATALOG_GENERATION=PASS models={len(MODELS)+len(MORE)+len(firmware.TABLES)}')
