"""Generate DrunkDeer physical layouts and tracking maps from reviewed Antler data.

Never execute vendor JavaScript or touch a user's settings. Conflicting factory
defaults are not tracking offsets: the B7 handler indexes the preview directly.
"""
import argparse
import hashlib
import json
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
import layout_import as m
from drunkdeer_layout_source import ROOT, MODELS

SOURCE=ROOT/'docs/research/drunkdeer-layout-sources/rectangles.json'
AUDIT=ROOT/'docs/research/drunkdeer-source-audit.json'
NAMES=('A75 ANSI','A75 Pro','A75 ISO','G60 ANSI','G65 ANSI','G75 ANSI','G75 JIS')
ENUMS=('A75Ansi','A75Pro','A75Iso','G60','G65','G75Ansi','G75Jis')
# Explicit reviewed differences between physical tracking arrays and factory
# defaults. End=99 also agrees with the previously shipped A75 analogue map.
OVERRIDES={'A75':{99:77},'A75Pro':{99:77},'A75_iso_uk':{75:50,85:100,99:77}}
LABELS={code:label for code,label in m.CODES.values()}
LABELS.update({0x409:'Fn',0x403:'Fn2'})


def rounded(v): return int(v.quantize(Decimal('1'),rounding=ROUND_HALF_UP))


def rectangles(k):
    x,y,w,h=(k[f] for f in ('x','y','w','h'))
    if k.get('notchW'):
        return [(x,y,w,k['notchY']),
                (x+k['notchW'],y+k['notchY'],w-k['notchW'],h-k['notchY'])]
    return [(x,y,w,h)]


def prepare(model, data, audit):
    keys=data['models'][model]
    factory=audit['models'][model]['factory']
    # Uniform physical scale, NOT per-row reflow. Preserve vendor offsets and
    # widths, including detached arrows. A normal key's height becomes 42 px.
    unit=Decimal(str(next(k['h'] for k in keys if k['value']==43)))
    scale=Decimal(42)/unit
    result=[]
    for k in keys:
        offset=k['value']
        hid=OVERRIDES.get(model,{}).get(offset,factory[offset]['hid'])
        m.require(hid in LABELS,f'Unknown physical identity: {model}:{offset}={hid}')
        x,y,w,h=(Decimal(str(k[n])) for n in ('x','y','w','h'))
        left,top=rounded(x*scale),rounded(y*scale)
        key=dict(hid=hid,label=LABELS[hid],x=left,y=top,
                 w=rounded((x+w)*scale)-left,h=rounded((y+h)*scale)-top,
                 trackingOffset=offset)
        if hid==40 and model in ('A75_iso_uk','G75JP'):
            # Straight notch edge in vendor transparent Enter assets:
            # A75 ISO 46/164 of width; G75 JP 52/220. Top part is one key high.
            notch=Decimal(46)/164 if model=='A75_iso_uk' else Decimal(52)/220
            key.update(notchW=rounded((x+w*notch)*scale)-left,notchY=42)
        result.append(key)
    m.require(len({k['hid'] for k in result})==len(result),'Duplicate HID identity')
    for i,a in enumerate(result):
        m.require(0<a['w']<=600 and 0<a['h']<=600,'Invalid dimensions')
        for b in result[i+1:]:
            m.require(not any(max(ax,bx)<min(ax+aw,bx+bw) and max(ay,by)<min(ay+ah,by+bh)
                for ax,ay,aw,ah in rectangles(a) for bx,by,bw,bh in rectangles(b)),
                f'Contour overlap: {model} {a["trackingOffset"]}/{b["trackingOffset"]}')
    return dict(name='DrunkDeer '+NAMES[MODELS.index(model)],brand='DrunkDeer',
                status='ready',unresolved=[],keys=result,
                sources=data['sources'],scale=str(scale),
                trackingOverrides=OVERRIDES.get(model,{}))


def products():
    data=json.loads(SOURCE.read_text(encoding='utf-8'))
    audit=json.loads(AUDIT.read_text(encoding='utf-8'))
    m.require(data['sources']['index.CJWCGjvj.js']==audit['sourceSha256'],'Source revisions differ')
    out={}
    header=['// Generated by tools/build_drunkdeer_layouts.py.','#pragma once']
    maps=['// Generated by tools/build_drunkdeer_layouts.py.','#pragma once',
          '#include "halljoy_drunkdeer_identity.h"','namespace halljoy::drunkdeer_identity {']
    for model,enum in zip(MODELS,ENUMS):
        report=prepare(model,data,audit)
        directory=ROOT/'docs/exports/drunkdeer'
        out[directory/(report['name']+'.ini')]=m.ini_text(report).encode('utf-16')
        out[directory/(model+'-review.json')]=(json.dumps(report,indent=2)+'\n').encode()
        header.append(f'static const KeyDef g_drunkdeer_{enum}[] = {{')
        mapping=[0]*126
        for k in report['keys']:
            mapping[k['trackingOffset']]=k['hid']
            fields=[k['hid'],min(20,k['y']//46),k['x'],k['w'],k['h'],k['y'],k.get('notchW',0),k.get('notchY',0)]
            header.append('    {L%s, %s},'%(json.dumps(k['label']),', '.join(map(str,fields))))
        header.append('};')
        maps.append(f'inline constexpr std::array<std::uint16_t,126> k{enum} = {{')
        maps.extend('    '+','.join(str(n) for n in mapping[i:i+21])+',' for i in range(0,126,21))
        maps.append('};')
    maps+=['inline constexpr const std::array<std::uint16_t,126>* TrackingMap(Model model) noexcept {','    switch(model) {']
    maps.extend(f'    case Model::{e}:return &k{e};' for e in ENUMS)
    maps+=['    default:return nullptr;','    }','}','}']
    out[ROOT/'src/HallJoyProject/HallJoy/drunkdeer_catalog_layouts.h']=('\n'.join(header)+'\n').encode()
    out[ROOT/'third_party/UniversalAnalogPluginFixed/halljoy_drunkdeer_maps.h']=('\n'.join(maps)+'\n').encode()
    return out


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');p.add_argument('--update',action='store_true');args=p.parse_args()
    if not SOURCE.exists() and not args.check:
        raw=(ROOT/'.local/research/layout-import-drunkdeer/dom-layouts.json').read_bytes()
        SOURCE.parent.mkdir(parents=True,exist_ok=True)
        with SOURCE.open('xb') as stream: stream.write(raw)
    for path,data in products().items():
        if path.exists():
            old=path.read_bytes()
            if args.update and not args.check:
                m.require(path.read_bytes()==old,'Concurrent change: '+str(path));path.write_bytes(data)
            else: m.require(old==data,'Changed generated output: '+str(path))
        else:
            m.require(not args.check,'Missing generated output: '+str(path))
            path.parent.mkdir(parents=True,exist_ok=True)
            with path.open('xb') as stream: stream.write(data)
    print('DRUNKDEER_CATALOG=PASS models=7')
