"""Generate exact IPI UUID/physical-ID profiles from locked firmware evidence."""
import hashlib,json,sys,re
from pathlib import Path
import prepare_ipi_layouts
ROOT=Path(__file__).resolve().parents[1]
AUDIT=ROOT/'docs/research/ipi-firmware-20260914/firmware-audit.json'
AUDIT_SHA='05101e1b6938b722a1cba8b4822e37e26ee2a4c8dcbbf5444a584183d436aaea'
def generate():
 assert hashlib.sha256(AUDIT.read_bytes()).hexdigest()==AUDIT_SHA
 rows=json.loads(AUDIT.read_bytes());reports=prepare_ipi_layouts.prepare()
 source=(prepare_ipi_layouts.SOURCE/'ipi-vendor-bytech-Dmk7DNgV.js').read_text(encoding='utf-8')
 pairs=re.findall(r'keycode:(\d+),id:(\d+)',source.split('pa=[',1)[1].split('],',1)[0])
 defaults={int(i):int(h) for h,i in pairs}
 def hid(value):
  if value==218103808:return 0x409
  if value>=65536:return 223+(value>>16).bit_length()
  return value
 factory=[hid(defaults.get(i,0)) for i in range(256)]
 lines=['#pragma once','#include <cstdint>','#include <cstddef>',
 '// Generated by build_ipi_native_catalog.py from UUID-matched firmware matrices.',
 'namespace ipi {',
 'struct Model { std::uint64_t uuid; const wchar_t* name; const char* product; const std::uint8_t* ids; std::size_t count; };']
 lines.append('inline constexpr std::uint16_t factoryHids[] = {'+', '.join(str(v) for v in factory)+'};')
 models=[]
 for report in reports:
  for product in report['identity']['products']:
   uuid=int(product,16);matches=[r for r in rows if int(r['uuid'],16)==uuid]
   assert matches and all(r['physical_ids']==matches[0]['physical_ids'] for r in matches)
   for r in matches:
    f=AUDIT.parent/r['file'];assert hashlib.sha256(f.read_bytes()).hexdigest()==r['sha256']
    assert r['geometry'] and all(not x['missing'] and not x['extra'] for x in r['geometry'])
   ids=matches[0]['physical_ids'];assert len(ids)==len(report['keys'])
   symbol='ids_'+product
   lines.append('inline constexpr std::uint8_t '+symbol+'[] = {'+', '.join(str(i) for i in ids)+'};')
   models.append('    {0x'+product+'ull, L"'+report['model']+'", "'+product+'", '+symbol+', '+str(len(ids))+'},')
 lines+=['inline constexpr Model models[] = {']+models+['};',
 'inline constexpr const Model* FindModel(std::uint64_t uuid) noexcept {',
 '    for (const auto& model : models) if (model.uuid == uuid) return &model;',
 '    return nullptr;', '}', '} // namespace ipi']
 return ('\n'.join(lines)+'\n').encode()
def main():
 data=generate();out=ROOT/'src/HallJoyProject/HallJoy/generated/ipi_models.h'
 if '--write-new' in sys.argv:
  with out.open('xb') as f:f.write(data)
 else:assert out.read_bytes()==data,'IPI native catalog drift'
 print('IPI_NATIVE_CATALOG=PASS models=8 source_hashes=18')
if __name__=='__main__':main()
