"""Lemokey-only catalog: official Launcher geometry + shipped UAP identities.

No HID access, downloaded code execution or inference from another model.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path
import layout_import as m

ROOT = Path(__file__).resolve().parents[1]
SOUP = ROOT/'third_party/UniversalAnalogPluginFixed/overlay/Soup/soup/AnalogueKeyboard.cpp'
SOURCE = ROOT/'docs/research/lemokey-layout-sources'
ALIASES = dict(BACKQUOTE='GRAVE', EQUALS='EQUAL', BRACKET_LEFT='LEFT_BRACKET',
               BRACKET_RIGHT='RIGHT_BRACKET', ARROW_LEFT='LEFT', ARROW_RIGHT='RIGHT',
               ARROW_UP='UP', ARROW_DOWN='DOWN', PERIOD='DOT', LCTRL='LCTL',
               RCTRL='RCTL', LMETA='LGUI', RMETA='RGUI', INTL_BACKSLASH='NUBS',
               LSHIFT='LSFT', RSHIFT='RSFT')


def prepare(variant, source=SOURCE, soup_path=SOUP):
    m.require(variant in ('ansi','iso'), 'Variant not supported by shipped UAP')
    pid = 0x0610 + (variant == 'iso')
    path = source/f'{0x362D0000+pid}.json'
    definition, digest = m.read_json(path)
    m.require(definition['vendorProductId'] == 0x362D0000+pid, 'Wrong device identity')
    m.require(definition['matrix'] == {'rows':6,'cols':15}, 'Wrong matrix dimensions')
    soup, soup_hash = m.read_source(soup_path)
    match = re.search(r'layout_lemokey_p1_he_'+variant+r'\[\]\s*=\s*\{(.*?)\};',soup,re.S)
    m.require(match is not None, 'Missing UAP matrix')
    body = re.sub(r'/\*.*?\*/|//[^\n]*','',match[1],flags=re.S)
    values = [part.strip() for part in body.split(',') if part.strip()]
    m.require(values[:2] == ['6','15'] and len(values)==92, 'UAP matrix changed')
    matrix = values[2:]
    keys = definition['layouts']['keys']
    positions = {(k['row'],k['col']) for k in keys}
    expected = {(i//15,i%15) for i,t in enumerate(matrix) if t!='KEY_NONE'} | {(0,14)}
    m.require(positions == expected, 'Geometry/UAP matrix sets differ')
    tokens, overrides = [], {}
    for k in keys:
        row,col = k['row'],k['col']
        key = matrix[row*15+col]
        token = 'KC_'+ALIASES.get(key[4:],key[4:])
        tokens.append(token)
        if key in ('KEY_FN','KEY_NONE'):
            m.require(key!='KEY_NONE' or (row,col)==(0,14), 'Unreviewed absent key')
            fix = dict(vendorProductId=definition['vendorProductId'],token=token,
                       reason='Shipped UAP P1 matrix: Fn is HallJoy 0x409; encoder has no analogue identity')
            fix.update(dict(hid=0x409,label='Fn') if key=='KEY_FN' else dict(exclude=True))
            overrides[f'{row},{col}']=fix
        else:
            m.require(token in m.CODES, f'Unreviewed UAP key: {key}')
    # Feed the existing strict geometry converter a reviewed simple physical
    # token map. This is UAP data, explicitly NOT a claimed QMK factory layer.
    info = dict(usb=dict(vid='0x362D',pid=hex(pid)),layouts=dict(
        LAYOUT_UAP=dict(layout=[dict(matrix=[k['row'],k['col']]) for k in keys])))
    code = '[UAP] = LAYOUT_UAP('+','.join(tokens)+')'
    report = m.convert(definition,info,code,'UAP',overrides)
    report['name']='Lemokey P1 HE '+variant.upper()
    m.require(report['status']=='ready', 'Unresolved actions')
    report['brand']='Lemokey'
    report['sources']=dict(launcher=dict(url=f'https://launcher.keychron.com/static/device/{0x362D0000+pid}/json/v3.json',sha256=digest),
                           uap=dict(path=soup_path.relative_to(ROOT).as_posix(),sha256=soup_hash))
    return report


def products():
    outputs={}
    header=['// Generated by tools/build_lemokey_layouts.py.','#pragma once']
    for variant in ('ansi','iso'):
        report=prepare(variant)
        out=ROOT/'docs/exports/lemokey-he'
        outputs[out/(report['name']+'.ini')]=m.ini_text(report).encode('utf-16')
        outputs[out/(variant+'-review.json')]=(json.dumps(report,indent=2)+'\n').encode()
        header.append(f'static const KeyDef g_lemokey_p1_{variant}[] = {{')
        for k in report['keys']:
            fields=[k['hid'],k['y']//46,k['x'],k['w'],k['h'],k['y'],k.get('notchW',0),k.get('notchY',0)]
            header.append('    {L%s, %s},' % (json.dumps(k['label']),', '.join(map(str,fields))))
        header.append('};')
    outputs[ROOT/'src/HallJoyProject/HallJoy/lemokey_catalog_layouts.h']=('\n'.join(header)+'\n').encode()
    return outputs


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    parser.add_argument('--update',action='store_true')
    args=parser.parse_args()
    for path,data in products().items():
        if path.exists():
            previous=path.read_bytes()
            if args.update and not args.check:
                m.require(path.read_bytes()==previous,f'Concurrent change: {path}')
                path.write_bytes(data)
            else:
                m.require(previous==data,f'Changed generated output: {path}')
        else:
            m.require(not args.check,f'Missing generated output: {path}')
            path.parent.mkdir(parents=True,exist_ok=True)
            with path.open('xb') as stream: stream.write(data)
    print('LEMOKEY_CATALOG=PASS variants=2')
