"""Extract reviewed legacy JingTai maps without executing vendor JavaScript."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/research/jingtai-v1/index-D22onkw6.js'
SHA = 'e9aebf1b6c1c452d1be8d9481e2838fcc26c0820ba648dd2fff3f617839e37aa'
HEADER = ROOT / 'src/HallJoyProject/HallJoy/jingtai_v1_profiles.h'
# Ambiguous inherited maps for MU68 Ultra/Polar75/MG75 are deliberately excluded.
MODELS = [('K', 'xMt', 'IROK NA87 Pro', 87),
          ('le', 'za', 'IYX MU68 Pro', 68),
          ('we', '_l', 'IROK ND63', 64),
          ('Ie', 'pIt', 'CAROTMAS Mercury68', 68),
          ('Te', 'pIt', 'CAROTMAS Mercury68 Pro', 68)]
NAMES = [
 ('K', ['IROK NA87 PRO', 'IROK NA87 PRO Universal']),
 ('le', ['IYX MU68 PRO', 'MU68 PRO', 'IYX MU68 PRO Cyan',
         'IYX MU68 PRO Universal', 'IYX MU68 PRO Cyan Universal']),
 ('we', ['IROK ND63', 'ND63 Cyan', 'IROK ND63 Cyan', 'IROK ND63 TTC',
         'IROK ND63 Universal', 'IROK ND63 Cyan Universal']),
 ('Ie', ['CAROTMAS Mer68']), ('Te', ['CAROTMAS Mer68 PRO'])]

def prepare():
    raw = SOURCE.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == SHA, 'Vendor source changed'
    s = raw.decode('utf-8')
    for wire in ['this.collectData(2)', 'createDataPacket(t,i){return Ws([92,4,18,0,t,i,255,255])}',
                 'o[0]===92&&o[1]===128&&o[2]===146', 's=s.slice(6)',
                 'i=this.dataCapturing[t]+this.dataCapturing[t+1]*256',
                 'this.parent.cmdKey(35', 'getVersion(){const t=Ws([92,2,1,0,255,255])']:
        assert wire in s, wire
    a=s.index('gs=[{Text:'); b=s.index('];',a)
    items=re.findall(r'Keys:new Map\(\[(.*?)\]\).*?VirtualKey:(\d+),HID:(\d+),Disable:',s[a:b])
    maps={}
    for name in ['za','xMt','_l','pIt']:
        body=re.search(r'\b'+re.escape(name)+r'=\{([^}]+)\}',s)[1]
        base=re.match(r'\.\.\.(\w+)',body)
        d=dict(maps[base[1]]) if base else {}
        d.update({int(k):int(v) for k,v in re.findall(r'(\d+):(\d+)',body)})
        maps[name]=d
    output=['#pragma once', '#include "mg75_pro_protocol.h"',
            '// Generated by tools/check_jingtai_v1_profiles.py; exact vendor evidence.',
            'namespace halljoy::jingtai_v1 {',
            'struct Model { const char* identity; const wchar_t* name; std::array<std::uint16_t,126> actions; unsigned count; unsigned range; };']
    for alias,table,label,count in MODELS:
        keys={int(m[1]) for entries,vk,hid in items
              if (m:=re.search(r'\['+alias+r',(\d+)\]',entries))}
        d={k:v for k,v in maps[table].items() if v in keys}
        assert len(keys)==len(d)==len(set(d.values()))==count
        assert set(d.values())==keys
        actions=[0]*126
        for index,selector in d.items():
            # Each 132-byte logical reply occupies three64-byte HID packets.
            # Vendor UI strips6 bytes then retains padding:93 slots per half.
            assert index<63 or 93<=index<156
            slot=index if index<63 else index-30
            assert not actions[slot]
            actions[slot]=0xf001 if selector==1 else selector
        output.append(f'inline constexpr Model model_{alias}{{"JT1-{alias.upper()}",L"{label}",{{{{'+','.join(map(str,actions))+f'}}}},{count},{3500 if alias in ("Ie","Te") else 4000}}};')
    for alias in ['le','we']:
        output.append(f'inline constexpr Model model_{alias}_cyan{{"JT1-{alias.upper()}-CYAN",model_{alias}.name,model_{alias}.actions,model_{alias}.count,3600}};')
    output += ['struct Identity { unsigned vid,pid; const wchar_t* product; const Model* model; };',
               'inline constexpr Identity identities[] = {']
    cc=s[s.index('cc=[{'):];cc=cc[:cc.index('];')]
    identities=[]
    for alias,names in NAMES:
        for name in names:
            entries=[x for x in re.findall(r'\{[^{}]+\}',cc) if f'productName:"{name}"' in x]
            assert len(entries)==1,(name,len(entries))
            entry=entries[0]
            fields={k:int(v) for k,v in re.findall(r'(\w+):(\d+)',entry)}
            assert fields['usagePage']==65440 and fields['usage']==1
            pairs=[(fields['vendorId'],fields['productId'])]
            if 'vendorId_new' in fields:pairs.append((fields['vendorId_new'],fields['productId_new']))
            for vid,pid in pairs:
                row=(vid,pid,name.upper(),alias)
                if row not in identities:identities.append(row)
    for vid,pid,name,alias in identities:
        profile=alias+'_cyan' if ('CYAN' in name or 'TTC' in name) else alias
        output.append(f' {{{vid},{pid},L"{name}",&model_{profile}}},')
    output += ['};',
      'inline bool Candidate(unsigned vid,unsigned pid) noexcept { for(const auto& i:identities) if(i.vid==vid&&i.pid==pid)return true; return false; }',
      'inline const Model* Find(unsigned vid,unsigned pid,std::wstring_view product) noexcept { for(const auto& i:identities) if(i.vid==vid&&i.pid==pid&&i.product==product)return i.model; return nullptr; }',
      '}']
    return '\n'.join(output)+'\n'

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--write',action='store_true');args=parser.parse_args()
    before=HEADER.read_bytes() if HEADER.exists() else None
    generated=prepare().encode()
    if args.write:
        assert (HEADER.read_bytes() if HEADER.exists() else None)==before
        if before is None:
            with HEADER.open('xb') as f:f.write(generated)
        else: HEADER.write_bytes(generated)
    else: assert before==generated,'Stale generated profiles'
    print('JINGTAI_V1_PROFILES=PASS models=5')
