"""Extract reviewed factory geometry from the pinned official desktop driver."""
import argparse
import hashlib
import json
import re
from pathlib import Path

SOURCES = [
    ("x65", "20e7e191", "4bb002fe54a61ba866fb40bae9c6a30d361b2296933860f00e08a6936093983d", 66),
    ("x68", "6a8f9cc7", "7614da6698661549450340f29a9a9073b8220da9ff8e3e1f61ad03c3716e4d7b", 66),
    ("x82", "b2a10b4e", "5c4c93b5566dc72aeead0977432b890cb57310211b25119abc3847c789d778dd", 83),
]
SPECIAL = {
    "Escape": ("Esc", 41), "Backspace": ("Back", 42), "Tab": ("Tab", 43),
    "CapsLock": ("Caps", 57), "Enter": ("Enter", 40), "Space": ("Space", 44),
    "Minus": ("-", 45), "Equal": ("=", 46), "BracketLeft": ("[", 47),
    "BracketRight": ("]", 48), "Backslash": (chr(92), 49), "Backquote": ("`", 53),
    "Semicolon": (";", 51), "Quote": ("'", 52), "Comma": (",", 54),
    "Period": (".", 55), "Slash": ("/", 56), "Delete": ("Del", 76),
    "Insert": ("Ins", 73), "Home": ("Home", 74), "End": ("End", 77),
    "PageUp": ("PgUp", 75), "PageDown": ("PgDn", 78),
    "ArrowRight": ("Right", 79), "ArrowLeft": ("Left", 80),
    "ArrowDown": ("Down", 81), "ArrowUp": ("Up", 82),
    "ControlLeft": ("Ctrl", 224), "ShiftLeft": ("Shift", 225),
    "AltLeft": ("Alt", 226), "MetaLeft": ("Win", 227),
    "ControlRight": ("Ctrl", 228), "ShiftRight": ("Shift", 229),
    "AltRight": ("Alt", 230), "Fn": ("Fn", 1033),
}
# Ordinary keyboard keys only. Encoder rotation/mute are not analog keys.
def usage(code):
    if code.startswith("Key"):
        return code[3:], ord(code[3:]) - ord("A") + 4
    if code.startswith("Digit"):
        return code[5:], 39 if code[5:] == "0" else 29 + int(code[5:])
    if re.fullmatch(r"F\d+", code):
        return code, 57 + int(code[1:])
    return SPECIAL[code]

def generate(driver):
    out = ['// Generated by tools/generate_attackshark_layouts.py; do not edit.', '#pragma once', '#include "keyboard_layout.h"']
    for model, chunk, digest, count in SOURCES:
        data = (driver / (chunk + ".js")).read_bytes()
        assert hashlib.sha256(data).hexdigest() == digest, chunk
        source = data.decode("utf8")
        keys = {}
        # SVG labels contain unescaped XML text (< and &); extract tagged key
        # groups directly, stopping at the next key or the end of this state.
        for code, body in re.findall(r'<g id="#([^"]+)">(.*?)(?=<g id="#|</svg>)', source, re.S):
            if code in keys:
                continue
            rect = re.search(r"<rect ([^>]+)>", body)
            assert rect and "transform=" not in rect[1], code
            attrs = dict(re.findall(r'([a-z]+)="([^"]+)"', rect[1]))
            keys[code] = [round(float(attrs[a])) for a in ("x", "y", "width", "height")]
        assert len(keys) == count, (model, len(keys))
        ox, oy = min(v[0] for v in keys.values()), min(v[1] for v in keys.values())
        rows = sorted({v[1] for v in keys.values()})
        hids = set()
        out += [f"// Official SVG {chunk}.js, SHA256 {digest}", f"static const KeyDef g_shark_{model}_ansi[] = {{"]
        ordered = sorted(keys.items(), key=lambda pair: (pair[1][1], pair[1][0]))
        for code, (x, y, w, h) in ordered:
            label, hid = usage(code)
            assert hid not in hids and w >= 18 and h >= 18
            hids.add(hid)
            for other, (xx, yy, ww, hh) in keys.items():
                assert other == code or not (x < xx+ww and xx < x+w and y < yy+hh and yy < y+h), (code, other)
            out.append(f'    {{L{json.dumps(label)}, {hid}, {rows.index(y)}, {x-ox}, {w}, {h}, {y-oy}, 0, 0}},')
        out.append("};")
    return chr(10).join(out) + chr(10)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("driver", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / "src/HallJoyProject/HallJoy/attackshark_pro_layouts.h"
    content = generate(args.driver).encode("utf8")
    if args.check:
        assert target.read_bytes() == content, "Generated geometry is stale"
    else:
        previous = target.read_bytes() if target.exists() else None
        if previous is None:
            with target.open("xb") as stream:
                stream.write(content)
        else:
            assert target.read_bytes() == previous
            target.write_bytes(content)
    print("ATTACK SHARK layouts: exact source hashes, key counts, usages and non-overlap PASS")
