"""Generate runtime yellow notices and reconcile them with a live Sheet snapshot.
Snapshot schema: list of {brand, model, status, color:{red,green,blue}}.
Use --sheet only with a freshly read Google Sheet export; never infer live sync
from the checked-in catalog alone.
"""
import argparse
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
CATALOG=ROOT/'docs/development/keyboard_support_notices.json'
HEADER=ROOT/'src/HallJoyProject/HallJoy/support_notice_catalog.h'
def render(data):
    lines=['// Generated by tools/support_notice_catalog.py. Edit the JSON catalog.',
           '#pragma once','#include <cstdint>','namespace halljoy::keyboard_support {',
           'inline unsigned NativeNotice(unsigned protocol, std::uint64_t token, bool connected) noexcept {',
           '    if(!connected || !token)return 0;', '    unsigned result=0;']
    seen=set()
    for group in data['groups']:
        assert group['models'] and group['flag']>0
        for model in group['models']:
            key=(model['brand'],model['model'])
            assert key not in seen,key
            seen.add(key)
            assert model['status']=='Implemented; awaiting hardware testing'
        condition=f"protocol=={group['protocol']}u"
        if group.get('tokens'):
            condition+=' && ('+' || '.join(f'token==0x{int(t,16):016X}ull' for t in group['tokens'])+')'
        if group.get('exclude'):condition+=f" && token!=0x{int(group['exclude'],16):016X}ull"
        lines.append(f"    if({condition})result|={group['flag']}u; // {group['id']}")
    return '\n'.join(lines+['    return result;','}','}'])+'\n'
def main():
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');p.add_argument('--sheet',type=Path);a=p.parse_args()
    data=json.loads(CATALOG.read_text(encoding='utf-8'));expected=render(data).encode()
    if a.write:
        old=HEADER.read_bytes() if HEADER.exists() else None
        if old is None:
            with HEADER.open('xb') as out:out.write(expected)
        elif old!=expected:
            assert HEADER.read_bytes()==old
            HEADER.write_bytes(expected)
    assert HEADER.read_bytes()==expected,'Generated runtime notices differ from catalog'
    wanted={(m['brand'],m['model']):m['status'] for g in data['groups'] for m in g['models']}
    if a.sheet:
        rows=json.loads(a.sheet.read_text(encoding='utf-8'))
        actual={(r.get('brand'),r.get('model')):r.get('status') for r in rows
                if r.get('color',{}).get('red',0)>=.8
                and r.get('color',{}).get('green',0)>=.8
                and r.get('color',{}).get('blue',1)<.8}
        assert actual==wanted,{'missing_or_wrong':[(k,v,actual.get(k)) for k,v in wanted.items() if actual.get(k)!=v],
                               'unexpected':[(k,v) for k,v in actual.items() if k not in wanted]}
    print(f'SUPPORT_NOTICE_CATALOG=PASS models={len(wanted)} live_sheet={bool(a.sheet)}')
if __name__=='__main__':main()

