#pragma once
#include "mg75_pro_protocol.h"
// Generated by tools/check_jingtai_v1_profiles.py; exact vendor evidence.
namespace halljoy::jingtai_v1 {
struct Model { const char* identity; const wchar_t* name; std::array<std::uint16_t,126> actions; unsigned count; unsigned range; };
inline constexpr Model model_K{"JT1-K",L"IROK NA87 Pro",{{41,58,59,60,61,62,63,64,65,66,67,68,69,0,70,71,72,0,0,0,0,53,30,31,32,33,34,35,36,37,38,39,45,46,42,73,74,75,0,0,0,0,43,20,26,8,21,23,28,24,12,18,19,47,48,49,76,77,78,0,0,0,0,57,4,22,7,9,10,11,13,14,15,51,52,0,40,0,0,0,0,0,0,0,225,0,29,27,6,25,5,17,16,54,55,56,0,229,0,82,0,0,0,0,0,224,227,226,0,0,0,44,0,0,0,230,61441,101,228,80,81,79,0,0,0,0}},87,4000};
inline constexpr Model model_le{"JT1-LE",L"IYX MU68 Pro",{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,41,30,31,32,33,34,35,36,37,38,39,45,46,42,73,0,0,0,0,0,0,43,20,26,8,21,23,28,24,12,18,19,47,48,49,76,0,0,0,0,0,0,57,4,22,7,9,10,11,13,14,15,51,52,0,40,75,0,0,0,0,0,0,225,0,29,27,6,25,5,17,16,54,55,56,229,82,78,0,0,0,0,0,0,224,227,226,0,0,0,44,0,0,230,61441,228,80,81,79,0,0,0,0,0,0}},68,4000};
inline constexpr Model model_we{"JT1-WE",L"IROK ND63",{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,41,30,31,32,33,34,35,36,37,38,39,45,46,42,0,0,0,0,0,0,0,43,20,26,8,21,23,28,24,12,18,19,47,48,49,0,0,0,0,0,0,0,57,4,22,7,9,10,11,13,14,15,51,52,0,40,0,0,0,0,0,0,0,225,0,29,27,6,25,5,17,16,54,55,56,229,82,99,0,0,0,0,0,0,224,227,226,0,0,0,44,0,0,230,61441,0,80,81,79,0,0,0,0,0,0}},64,4000};
inline constexpr Model model_Ie{"JT1-IE",L"CAROTMAS Mercury68",{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,41,30,31,32,33,34,35,36,37,38,39,45,46,42,73,0,0,0,0,0,0,43,20,26,8,21,23,28,24,12,18,19,47,48,49,76,0,0,0,0,0,0,57,4,22,7,9,10,11,13,14,15,51,52,0,40,75,0,0,0,0,0,0,225,0,29,27,6,25,5,17,16,54,55,56,229,82,78,0,0,0,0,0,0,224,227,226,0,0,0,44,0,0,230,61441,228,80,81,79,0,0,0,0,0,0}},68,3500};
inline constexpr Model model_Te{"JT1-TE",L"CAROTMAS Mercury68 Pro",{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,41,30,31,32,33,34,35,36,37,38,39,45,46,42,73,0,0,0,0,0,0,43,20,26,8,21,23,28,24,12,18,19,47,48,49,76,0,0,0,0,0,0,57,4,22,7,9,10,11,13,14,15,51,52,0,40,75,0,0,0,0,0,0,225,0,29,27,6,25,5,17,16,54,55,56,229,82,78,0,0,0,0,0,0,224,227,226,0,0,0,44,0,0,230,61441,228,80,81,79,0,0,0,0,0,0}},68,3500};
inline constexpr Model model_le_cyan{"JT1-LE-CYAN",model_le.name,model_le.actions,model_le.count,3600};
inline constexpr Model model_we_cyan{"JT1-WE-CYAN",model_we.name,model_we.actions,model_we.count,3600};
struct Identity { unsigned vid,pid; const wchar_t* product; const Model* model; };
inline constexpr Identity identities[] = {
 {7247,61064,L"IROK NA87 PRO",&model_K},
 {7330,1025,L"IROK NA87 PRO",&model_K},
 {7247,61064,L"IROK NA87 PRO UNIVERSAL",&model_K},
 {7330,1025,L"IROK NA87 PRO UNIVERSAL",&model_K},
 {7247,61064,L"IYX MU68 PRO",&model_le},
 {7330,1026,L"IYX MU68 PRO",&model_le},
 {7247,61064,L"MU68 PRO",&model_le},
 {7330,1026,L"MU68 PRO",&model_le},
 {7247,61064,L"IYX MU68 PRO CYAN",&model_le_cyan},
 {7330,1026,L"IYX MU68 PRO CYAN",&model_le_cyan},
 {7247,61064,L"IYX MU68 PRO UNIVERSAL",&model_le},
 {7330,1026,L"IYX MU68 PRO UNIVERSAL",&model_le},
 {7247,61064,L"IYX MU68 PRO CYAN UNIVERSAL",&model_le_cyan},
 {7330,1026,L"IYX MU68 PRO CYAN UNIVERSAL",&model_le_cyan},
 {7247,61064,L"IROK ND63",&model_we},
 {7330,1030,L"IROK ND63",&model_we},
 {7247,61064,L"ND63 CYAN",&model_we_cyan},
 {7330,1030,L"ND63 CYAN",&model_we_cyan},
 {7247,61064,L"IROK ND63 CYAN",&model_we_cyan},
 {7330,1030,L"IROK ND63 CYAN",&model_we_cyan},
 {7247,61064,L"IROK ND63 TTC",&model_we_cyan},
 {7330,1030,L"IROK ND63 TTC",&model_we_cyan},
 {7247,61064,L"IROK ND63 UNIVERSAL",&model_we},
 {7330,1030,L"IROK ND63 UNIVERSAL",&model_we},
 {7247,61064,L"IROK ND63 CYAN UNIVERSAL",&model_we_cyan},
 {7330,1030,L"IROK ND63 CYAN UNIVERSAL",&model_we_cyan},
 {7333,2054,L"CAROTMAS MER68",&model_Ie},
 {7333,2054,L"CAROTMAS MER68 PRO",&model_Te},
};
inline bool Candidate(unsigned vid,unsigned pid) noexcept { for(const auto& i:identities) if(i.vid==vid&&i.pid==pid)return true; return false; }
inline const Model* Find(unsigned vid,unsigned pid,std::wstring_view product) noexcept { for(const auto& i:identities) if(i.vid==vid&&i.pid==pid&&i.product==product)return i.model; return nullptr; }
}
