// Generated by tools/build_keychron_layouts.py.
#pragma once
#define HALLJOY_KEYCHRON_CATALOG_PRESETS \
    { L"Keychron K2 HE ANSI", g_catalog_k2, (int)std::size(g_catalog_k2), L"Keychron" }, \
    { L"Keychron Q3 HE ANSI", g_catalog_q3, (int)std::size(g_catalog_q3), L"Keychron" }, \
    { L"Keychron Q5 HE ANSI", g_catalog_q5, (int)std::size(g_catalog_q5), L"Keychron" }, \
    { L"Keychron K2 HE ISO", g_catalog_k2_iso, (int)std::size(g_catalog_k2_iso), L"Keychron" }, \
    { L"Keychron K2 HE JIS", g_catalog_k2_jis, (int)std::size(g_catalog_k2_jis), L"Keychron" }, \
    { L"Keychron K4 HE ISO", g_catalog_k4_iso, (int)std::size(g_catalog_k4_iso), L"Keychron" }, \
    { L"Keychron K4 HE JIS", g_catalog_k4_jis, (int)std::size(g_catalog_k4_jis), L"Keychron" }, \
    { L"Keychron K8 HE ANSI", g_catalog_k8_ansi, (int)std::size(g_catalog_k8_ansi), L"Keychron" }, \
    { L"Keychron K8 HE ISO", g_catalog_k8_iso, (int)std::size(g_catalog_k8_iso), L"Keychron" }, \
    { L"Keychron K8 HE JIS", g_catalog_k8_jis, (int)std::size(g_catalog_k8_jis), L"Keychron" }, \
    { L"Keychron K10 HE ANSI", g_catalog_k10_ansi, (int)std::size(g_catalog_k10_ansi), L"Keychron" }, \
    { L"Keychron K10 HE ISO", g_catalog_k10_iso, (int)std::size(g_catalog_k10_iso), L"Keychron" }, \
    { L"Keychron Q1 HE ISO", g_catalog_q1_iso, (int)std::size(g_catalog_q1_iso), L"Keychron" }, \
    { L"Keychron Q1 HE JIS", g_catalog_q1_jis, (int)std::size(g_catalog_q1_jis), L"Keychron" }, \
    { L"Keychron Q3 HE ISO", g_catalog_q3_iso, (int)std::size(g_catalog_q3_iso), L"Keychron" }, \
    { L"Keychron Q3 HE JIS", g_catalog_q3_jis, (int)std::size(g_catalog_q3_jis), L"Keychron" }, \
    { L"Keychron Q5 HE ISO", g_catalog_q5_iso, (int)std::size(g_catalog_q5_iso), L"Keychron" }, \
    { L"Keychron Q5 HE JIS", g_catalog_q5_jis, (int)std::size(g_catalog_q5_jis), L"Keychron" }, \
    { L"Keychron Q6 HE ANSI", g_catalog_q6_ansi, (int)std::size(g_catalog_q6_ansi), L"Keychron" }, \
    { L"Keychron Q6 HE ISO", g_catalog_q6_iso, (int)std::size(g_catalog_q6_iso), L"Keychron" }, \
    { L"Keychron Q6 HE JIS", g_catalog_q6_jis, (int)std::size(g_catalog_q6_jis), L"Keychron" }, \
    { L"Keychron Q12 HE ANSI", g_catalog_q12_ansi, (int)std::size(g_catalog_q12_ansi), L"Keychron" }, \
    { L"Keychron Q12 HE ISO", g_catalog_q12_iso, (int)std::size(g_catalog_q12_iso), L"Keychron" }, \
    { L"Keychron Q1 HE 8K ANSI", g_catalog_q1_8k_ansi, (int)std::size(g_catalog_q1_8k_ansi), L"Keychron" }, \
    { L"Keychron Q1 HE 8K ISO", g_catalog_q1_8k_iso, (int)std::size(g_catalog_q1_8k_iso), L"Keychron" }, \
    { L"Keychron Q1 HE 8K JIS", g_catalog_q1_8k_jis, (int)std::size(g_catalog_q1_8k_jis), L"Keychron" }, \
    { L"Keychron Q3 HE 8K ANSI", g_catalog_q3_8k_ansi, (int)std::size(g_catalog_q3_8k_ansi), L"Keychron" }, \
    { L"Keychron Q3 HE 8K ISO", g_catalog_q3_8k_iso, (int)std::size(g_catalog_q3_8k_iso), L"Keychron" }, \
    { L"Keychron Q3 HE 8K JIS", g_catalog_q3_8k_jis, (int)std::size(g_catalog_q3_8k_jis), L"Keychron" }, \
    { L"Keychron Q6 HE 8K ANSI", g_catalog_q6_8k_ansi, (int)std::size(g_catalog_q6_8k_ansi), L"Keychron" }, \
    { L"Keychron Q5 HE 8K ANSI", g_catalog_q5_8k_ansi, (int)std::size(g_catalog_q5_8k_ansi), L"Keychron" }, \
    { L"Keychron K3 HE ANSI", g_catalog_k3_ansi, (int)std::size(g_catalog_k3_ansi), L"Keychron" }, \
    { L"Keychron K3 HE ISO", g_catalog_k3_iso, (int)std::size(g_catalog_k3_iso), L"Keychron" }, \
    { L"Keychron K3 HE JIS", g_catalog_k3_jis, (int)std::size(g_catalog_k3_jis), L"Keychron" },
