// Generated by tools/support_notice_catalog.py. Edit the JSON catalog.
#pragma once
#include <cstdint>
namespace halljoy::keyboard_support {
inline unsigned NativeNotice(unsigned protocol, std::uint64_t token, bool connected, unsigned productId=0) noexcept {
    if(!connected)return 0;
    unsigned result=0;
    if(protocol==17u && token!=0x5348583635414E53ull && !(token==0x683D58FC5C0C5E90ull && productId==20521u))result|=256u; // AttackShark
    if(protocol==12u)result|=8u; // Hero84
    if(protocol==6u && (token==0x57494E363050524Full || token==0x57494E363850524Full || token==0x484552363850524Full))result|=8192u; // AulaRm
    if(protocol==6u && (token==0x98E6602F43E0E69Cull || token==0x93B5A992A4E00487ull))result|=512u; // GravaStar
    if(protocol==3u && (token==0x798EDA38A47F0E95ull || token==0x36A3739BD6AEEEF8ull || token==0xBEE2B020B2BFBA27ull))result|=1024u; // Ipi
    if(protocol==18u)result|=128u; // Mg75Pro
    if(protocol==7u && (token==0xF3B7ECFB2D628746ull || token==0x4B36313700000001ull || token==0x4B36313700000002ull))result|=2048u; // Redragon
    if(protocol==20u)result|=16384u; // Slice75
    if(protocol==21u)result|=32768u; // RongYuan
    if(protocol==22u)result|=65536u; // RongYuanStream
    if(protocol==23u)result|=131072u; // TartarusPro
    if(protocol==24u)result|=262144u; // Neo65
    if(protocol==4u && (token==0x000000001CA60528ull || token==0x000000001CA6052Aull || token==0x000000001CA6052Cull || token==0x000000001CA60531ull || token==0x000000001CA6052Bull || token==0x000000001CA6052Dull || token==0x000000001CA60540ull || token==0x000000001CA61C0Aull || token==0x000000001CA61C0Cull || token==0x000000001CA61C12ull || token==0x000000001CA61C14ull || token==0x000000001CA61C1Aull || token==0x000000001CA61C1Full || token==0x000000001CA61C23ull || token==0x000000001CA61C24ull || token==0x000000001CA61C2Bull || token==0x000000001CA61C2Cull || token==0x000000001CA61C2Full || token==0x000000001CA61C37ull || token==0x000000001CA61C3Cull || token==0x000000001CA61C3Dull || token==0x000000001CA61C45ull || token==0x000000001CA61C4Aull || token==0x000000001CA61C4Cull || token==0x000000001CA62708ull || token==0x000000001CA62709ull || token==0x000000001CA6270Aull || token==0x000000001CA65E01ull))result|=524288u; // SparkLinkV2
    return result;
}
}
