#pragma once

#define HALLJOY_VERSION_MAJOR 1
#define HALLJOY_VERSION_MINOR 4
#define HALLJOY_VERSION_PATCH 1
#define HALLJOY_VERSION_BUILD 0

#define HALLJOY_VERSION_TUPLE 1,4,1,0
#define HALLJOY_VERSION_STRING "1.4.1"
#define HALLJOY_VERSION_STRING_FULL "1.4.1.0"
#define HALLJOY_VERSION_WSTRING L"1.4.1"
#define HALLJOY_BUILD_ID_W L"HallJoy-v1.4"
#define HALLJOY_ABOUT_VERSION_STRING "HallJoy, Version 1.4.1"
